const firstDay = "Monday";
const secondDay = "Friday";
console.log(`Available days: ${firstDay} and ${secondDay}`);
const deliveryDay = "Friday";
console.log(`Delivery Day: ${deliveryDay}`);
const firstDayCheck = deliveryDay === firstDay;
console.log(`Successful delivey on the first day? ${firstDayCheck}`);
const secondDayCheck = deliveryDay === secondDay;
console.log(`Successful delviery on the second day? ${secondDayCheck}`);
const dayResult = firstDayCheck || secondDayCheck === true;
console.log(`Fulfilled Sheila's day preference? ${dayResult}`);
const requestAfterTime = 8;
const requestBeforeTime = 10;
console.log(`Request deliver after ${requestAfterTime} but before ${requestBeforeTime}`);
const deliveryTime = 9;
console.log(`Delivery Time: ${deliveryTime}`);
const afterTimeCheck = requestAfterTime <= deliveryTime;
console.log(`Delivery is after ${requestAfterTime}? ${afterTimeCheck}`);
const beforeTimeCheck = requestBeforeTime >= deliveryTime;
console.log(`Delivery is before ${requestBeforeTime}? ${beforeTimeCheck}`);
const timeResult = beforeTimeCheck && afterTimeCheck === true;
console.log(`Fulfilled Sheila's time preference? ${timeResult}`);
const overallCheck = timeResult && dayResult === true;
console.log(`Program scheduled well? ${overallCheck}`);